package Sort;

public enum AlgorithmMode {
	NULL, GNOME,
	BINARY_INSERTION,
	
	BUBBLE, BUBBLE2, PANCAKE, INSERTION, COMB, LOMUTO_QUICK, HOARE_QUICK, HEAP, COCKTAIL, SHELL, SLOW, THREEWAY_QUICK, INTRO, 
	BOGO, STOOGE, SLEEP, BOZO, SELECTION, PIGEONHOLE, COUNT, LSD_RADIX, AMERICAN_FLAG, MERGE, BUCKET, TIM, THREEWAY_MERGE, 
	ODD_EVEN, HYBRID_QUICK, CYCLE, STRAND, BITONIC, BATCHER_ODD_EVEN_MERGE
}
